branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.2
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
install:
- |
  gem update cocoapods
  brew update
  brew reinstall xctool
  pod install
script:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    xctool -workspace FBKVOController.xcworkspace -scheme FBKVOController -sdk iphonesimulator build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint KVOController.podspec
    pod lib lint --use-libraries KVOController.podspec
  fi
after_success:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
